flag_management:
  default_rules: # the rules that will be followed for any flag added, generally
    carryforward: false
    statuses:
      - type: project
        target: 75 # the default target for the project
        threshold: 2 # the amount coverage can decrease by
      - type: patch
        target: 80%
